### ISSUE TITLE
Logging issues

### ISSUE THREAD

**Issue by makarovNick** [Jingnan-Jia/segmentation_metrics#23]
There is issue with logging in "sg.write_metrics".
seg-metrics==1.1.3
        
--- Logging error ---                                                                                                   
Traceback (most recent call last):                                                                                        
File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit                                                         
            msg = self.format(record)                                                                                             
File "/usr/lib/python3.9/logging/__init__.py", line 927, in format                                                        
            return fmt.format(record)                                                                                             
File "/usr/lib/python3.9/logging/__init__.py", line 663, in format                                                        
            record.message = record.getMessage()                                                                                  
File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage                                                    
            msg = msg % self.args                                                                                               
TypeError: not all arguments converted during string formatting                                                         
           Call stack:
...
        sg.write_metrics(labels=[1], gdth_img=gt, pred_img=pred, verbose=False,                                     
File "/home/nmakarov/sg/lib/python3.9/site-packages/seg_metrics/seg_metrics.py", line 355, in write_metrics               
         metrics_dict_all_labels = get_metrics_dict_all_labels(labels, gdth, pred, spacing=gdth_spacing[::-1],                 
File "/home/nmakarov/sg/lib/python3.9/site-packages/seg_metrics/seg_metrics.py", line 213, in get_metrics_dict_all_labels                                                                                                                         
         logging.info('\nstart to get metrics for label: ', label)                                                         
Message: '\nstart to get metrics for label: '                                                                           
Arguments: (1,)

**Comment by Jingnan-Jia** [comment]
@makarovNick I feel very sorry for my late reply. Thank you for your issue. I just updated the code and fix the bug. Now you could re-install the package and this issue will disappear in the latest version of v1.1.5.

Best,
Jingnan
